# Dependencies
markdown: kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Code Lụm
#tagline:          'A Jekyll theme'
description:      '  <br><br><br><br><br>  Blog này là nơi mình chia sẻ chút kiến thức ít ỏi của bản thân về mọi thứ xung quanh.'
#description: 'ddcddcdd'
url:              https://merlin7vv4.github.io/
baseurl:          https://merlin7vv4.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
